///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String fontsMontserratMedium = 'assets/fonts/Montserrat-Medium.ttf';
  static const String fontsMontserratRegular = 'assets/fonts/Montserrat-Regular.ttf';
  static const String userImage1 = 'assets/images/user_image1.svg';
  static const String userImage2 = 'assets/images/user_image3.svg';
  static const String userImage3 = 'assets/images/user_image2.svg';
  static const String imagesBalance = 'assets/images/balance.svg';
  static const String imagesCardBackground = 'assets/images/card_background.png';
  static const String imagesDashboard = 'assets/images/dashboard.svg';
  static const String imagesExpenses = 'assets/images/expenses.svg';
  static const String imagesGallery = 'assets/images/gallery.svg';
  static const String imagesIncome = 'assets/images/income.svg';
  static const String imagesLogout = 'assets/images/logout.svg';
  static const String imagesMyInvestments = 'assets/images/my_investments.svg';
  static const String imagesMyTransctions = 'assets/images/my_transctions.svg';
  static const String imagesSettings = 'assets/images/settings.svg';
  static const String imagesStatistics = 'assets/images/statistics.svg';
  static const String imagesWalletAccount = 'assets/images/wallet_account.svg';

}
